version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-uea-lyceum
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: uea-lyceum
      MYSQL_USER: ueateste
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql